# Generated by Django 5.2.1 on 2025-05-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GunsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gun',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gun',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='brand',
            field=models.CharField(default='Someones Guns', max_length=100),
        ),
    ]
